<section class="titleArea">
    <div class="titleAreaInner">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="titleAreaContent">
                        <h1><?php echo $title; ?></h1>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<section class="aboutSection section-padding">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-md-12 col-sm-12">
                <div class="titleAreaContent policy-content">
                    <h3>1. READ THIS:</h3>
                    <p>This Terms of Use Agreement (“Agreement” or “Terms of Use”) is made by and between FAVORITE WISH, LTD CO, a SC company,(“FAVORITE WISH, LTD CO”) and you (“you,” “your” or “User”). This Agreement contains the terms and conditions that govern your use of this Website.</p>
                    <p>By accessing or attempting to interact with any part of this website, or other favorite wish, ltd co software, services, websites or any of favorite wish, ltd co licensees’ services (collectively “services”), you agree that you have read, understand and agree to be bound by this agreement. If you do not agree to be bound by this agreement, do not access or use any part of this website.</p>
                    <p>Favorite wish, ltd co reserves the right, from time to time, with or without notice to you, to make changes to this agreement in favorite wish, ltd co’s sole discretion. Continued use of any part of this website constitutes your acceptance of such changes. The most current version of this agreement, which supersedes all previous versions, can be reviewed by clicking on the terms of use hyperlink located at the bottom of every page on this website.</p>
                    <p>No implication is made that the materials published on FAVORITE WISH, LTD CO’s website(s) are appropriate for use outside of the United States. If you access this website from outside of the United States, you do so on your own initiative and you are responsible for compliance with local laws. Additionally, this website is published in english and we are not responsible for errors in translation.</p>
                    <h3>2. ACCESS TO THIS SITE</h3>
                    <p>To access this site or some of the resources it offers, you may be asked to provide certain registration details or other information. It is a condition of your use of this site that all the information you provide on this site will be correct, current, and complete. If FAVORITE WISH, LTD CO believes the information you provide is not correct, current, or complete, FAVORITE WISH, LTD CO has the right to refuse you access to this site or any of its resources, and to terminate or suspend your access at any time.</p>
                    <h3>3. RESTRICTIONS ON USE</h3>
                    <p>You may use this site for purposes expressly permitted by this site. As a condition of your use of FAVORITE WISH, LTD CO's website(s), you warrant to FAVORITE WISH, LTD CO that you will not use the website(s) for any purpose that is unlawful or prohibited by these terms, conditions, and notices. For example, you may not (and may not authorize any party to) (i) co-brand this site, or (ii) frame this site, or (iii) download any content from this site (other than as provided by these terms) without the express prior written permission of an authorized representative of FAVORITE WISH, LTD CO.  For purposes of these Terms of Use, co-branding means to display a name, logo, trademark, or other means of attribution or identification of any party in such a manner as is reasonably likely to give a user the impression that such other party has the right to display, publish, or distribute this site or content accessible within this site. You agree to cooperate with FAVORITE WISH, LTD CO to prevent or remedy any unauthorized use. In addition, you may not use FAVORITE WISH, LTD CO's website(s) in any manner which could disable, overburden, damage, or impair the website(s) or interfere with any other party's use and enjoyment of the website(s). You may not obtain or attempt to obtain any materials, content, or information through any means not intentionally made available or provided for through the website(s).</p>
                    <h3>4.  PERSONAL AND NON-COMMERCIAL USE LIMITATION</h3>
                    <p>FAVORITE WISH, LTD CO's website(s) are for your personal and non-commercial use, unless otherwise specified. You may not use this site for any other purpose, including any commercial purpose, without FAVORITE WISH, LTD CO's express prior written consent. You may not modify, copy, distribute, display, send, perform, reproduce, publish, license, create derivative works from, transfer, or sell any information, content, software, products or services obtained from or otherwise connected to FAVORITE WISH, LTD CO's website(s), unless expressly permitted by these terms.</p>
                    <h3>5.  PROPRIETARY INFORMATION</h3>
                    <p>The material and content accessible from this site, and any other website owned, operated, licensed, or otherwise controlled by FAVORITE WISH, LTD CO (the “Content”) is the proprietary information of FAVORITE WISH, LTD CO or the party that provided or licensed the Content to FAVORITE WISH, LTD CO whereby such providing party retains all right, title, and interest in the Content. Accordingly, the Content may not be copied, distributed, republished, uploaded, posted, or transmitted in any way without the prior written consent of FAVORITE WISH, LTD CO, except that you may print out a copy of the Content solely for your personal use, and you may re-post a single image and up to one hundred (100) words of continuous text from any article if such posting provides a right of attribution to FAVORITE WISH, LTD CO, and promotes the article on other websites, including social media sites.  In doing so, you may not remove or alter, or cause to be removed or altered, any copyright, trademark, trade name, service mark, or any other proprietary notice or legend appearing on any of the Content.  Modification or use of the Content except as expressly provided in these Terms of Use violates FAVORITE WISH, LTD CO's intellectual property rights. Neither title nor intellectual property rights are transferred to you by access to this site.</p>
                    <p>From time to time, the website will utilize various plugins or widgets to allow sharing of content via social media channels, email or other methods. Use of these plugins or widgets does not constitute any waiver of FAVORITE WISH, LTD CO’s intellectual property rights. Such use is a limited license to republish the content on the approved social media channels, with full credit to the website.</p>
                    <h3>6.  LINKS TO THIRD-PARTY WEBSITES</h3>
                    <p>This site may link to other sites which are not maintained by, or related to, FAVORITE WISH, LTD CO. You represent and warrant that you have read and agree to be bound by all applicable Terms of Use and policies for any third-party websites. Links to such sites are provided as a service to users and are not sponsored by or affiliated with this site or FAVORITE WISH, LTD CO.  FAVORITE WISH, LTD CO has not reviewed any or all of such sites and is not responsible for the content of those sites. Links are to be accessed at the user's own risk, and FAVORITE WISH, LTD CO makes no representations or warranties about the content, completeness or accuracy of the sites linked to or from this site. You expressly hold FAVORITE WISH, LTD CO harmless from any and all liability related to your use of a third-party website. FAVORITE WISH, LTD CO provides links as a convenience, and the inclusion of any link to a third-party site does not imply endorsement by FAVORITE WISH, LTD CO of that site or any association with its operators.</p>
                    <h3>7.  USE OF COMMUNICATION SERVICES   </h3>
                    <p>FAVORITE WISH, LTD CO's websites may contain comment boxes, forums, bulletin board services, chat areas, message boards, news groups, communities, personal web pages, calendars, and/or other message or communication facilities designed to allow you to communicate with the Internet community or with a group (collectively, “Communications Services”). You agree to use the Communication Services only to post, send and receive messages and content that are proper and related to the particular Communication Service. Users agree to adhere to this Terms of Use agreement when using FAVORITE WISH, LTD CO’s Communication Services.</p>
                    <p>When using the Communication Services, you agree that you will not post, send, submit, publish, or transmit in connection with this site any material that:</p>
                    <ul>
                        <li>You do not have the right to post, including proprietary material of any third party, such as files containing software or other material protected by intellectual property laws (or by rights of privacy or publicity);</li>
                        <li>Advocates illegal activity or discusses an intent to commit an illegal act;</li>
                        <li>Is vulgar, obscene, ***graphic, or indecent;</li>
                        <li>Does not pertain directly to this site;</li>
                        <li>Threatens or abuses others, libels, defames, invades privacy, stalks, is obscene, ***graphic, racist, abusive, harassing, threatening or offensive;</li>
                        <li>Seeks to exploit or harm children by exposing them to inappropriate content, asking for personally identifiable details or otherwise;</li>
                        <li>Harvests or otherwise collects information about others, including e-mail addresses, without their consent;</li>
                        <li>Violates any law or may be considered to violate any law;</li>
                        <li>Impersonates or misrepresents your connection to any other entity or person or otherwise manipulates headers or identifiers to disguise the origin of the content;</li>
                        <li>Falsifies or deletes any author attributions, legal or other proper notices or proprietary designations or labels of the origin or source of software or other material contained in a file that is permissibly uploaded;</li>
                        <li>Advertises any commercial endeavor (e.g., offering for sale products or services) or otherwise engages in any commercial activity (e.g., conducting raffles or contests, displaying sponsorship banners, and/or soliciting goods or services) except as may be specifically authorized on this site;</li>
                        <li>Solicits funds, advertisers or sponsors;</li>
                        <li>Includes programs that contain viruses, worms and/or Trojan horses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer software or hardware or telecommunications;</li>
                        <li>Disrupts the normal flow of dialogue, causes a screen to scroll faster than other users are able to type, or otherwise act in a way which affects the ability of other people to engage in real time activities via this site;</li>
                        <li>Includes MP3 format files;</li>
                        <li>Amounts to a pyramid or other like scheme, including contests, chain letters, and surveys;</li>
                        <li>Disobeys any policy or regulations including any code of conduct or other guidelines, established from time to time regarding use of this site or any networks connected to this site;</li> or
                        <li>Contains hyper-links to other sites that contain content that falls within the descriptions set forth above.</li>
                    </ul>
                    <p>FAVORITE WISH, LTD CO reserves the right to monitor use of this site to determine compliance with these Terms of Use, as well as the right to remove or refuse any information for any reason. FAVORITE WISH, LTD CO reserves the right to terminate your access to any or all of the Communication Services at any time without notice for any reason whatsoever. FAVORITE WISH, LTD CO also reserves the right at all times to disclose any information as necessary to satisfy any applicable law, regulation, legal process or governmental request, or to edit, refuse to post or to remove any information or materials, in whole or in part, in its sole discretion. Materials uploaded to a Communication Service may be subject to posted limits on use, reproduction and/or dissemination and you are responsible for abiding by such limitations with respect to your submissions, including any downloaded materials.</p>
                    <p>Notwithstanding these rights, you remain solely responsible for the content of your submissions. You acknowledge and agree that neither FAVORITE WISH, LTD CO nor any third party that provides Content to FAVORITE WISH, LTD CO will assume or have any liability for any action or inaction by FAVORITE WISH, LTD CO or such third party with respect to any submission. FAVORITE WISH, LTD CO cautions you against giving out any personally identifying information about yourself in any Communication Service. FAVORITE WISH, LTD CO does not control or endorse the content, messages or information found in any Communication Service and, consequently, FAVORITE WISH, LTD CO specifically disclaims any liability with respect to the Communication Services and any actions resulting from your participation in any Communication Service. Managers and hosts are not authorized FAVORITE WISH, LTD CO spokespersons, and their views do not necessarily reflect those of FAVORITE WISH, LTD CO.</p>
                    <h3>8.  SUBMISSIONS</h3>
                    <p>Unless you and FAVORITE WISH, LTD CO enter into a separate written contract for use of your Content that states otherwise, you hereby grant to FAVORITE WISH, LTD CO the royalty-free, perpetual, irrevocable, worldwide, non-exclusive right and license to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, perform, and display all content, remarks, suggestions, ideas, graphics, or other information communicated to FAVORITE WISH, LTD CO through this site (together, the “Submission”), and to incorporate any Submission in other works in any form, media, or technology now known or later developed. FAVORITE WISH, LTD CO will not be required to treat any Submission as confidential, and may use any Submission in its business (including without limitation, for products or advertising) without incurring any liability for royalties or any other consideration of any kind, and will not incur any liability as a result of any similarities that may appear in future FAVORITE WISH, LTD CO operations.
FAVORITE WISH, LTD CO will treat any personal information that you submit through this site in accordance with its Terms of Use
</p>
                    <h3>9.  DISCLAIMER</h3>
                    <p>FAVORITE WISH, LTD CO has made every effort to ensure that all information on the website has been tested for accuracy. FAVORITE WISH, LTD CO make no guarantees regarding the results that you will see from using the information provided on the website.</p>
                    <p>The website was developed strictly for informational purposes. You understand and agree that you are fully responsible for your use of the information provided on the website. FAVORITE WISH, LTD CO makes no representations, warranties, or guarantees. You understand that results may vary from person to person. FAVORITE WISH, LTD CO assumes no responsibility for errors or omissions that may appear on the website.</p>
                    <p>You understand that FAVORITE WISH, LTD CO cannot and does not guarantee or warrant that files available for downloading from the Internet will be free of viruses, worms, Trojan horses or other code that may manifest contaminating or destructive properties. The website is provided on an “as is” and “as available” basis without any representations or warranties, expressed or implied. You are responsible for implementing sufficient procedures and checkpoints to satisfy your particular requirements for accuracy of data input and output, and for maintaining a means external to this site for any reconstruction of any lost data. FAVORITE WISH, LTD CO does not assume any responsibility or risk for your use of the Internet.</p>
                    <p>The Content is not necessarily complete and up-to-date and should not be used to replace any written reports, statements, or notices provided by FAVORITE WISH, LTD CO.</p>
                    <p>Your use of this site is at your own risk. The content is provided as is and without warranties of any kind, either expressed or implied. Favorite wish, ltd co disclaims all warranties, including any implied warranties of merchantability, fitness for a particular purpose, title, or non-infringement. Favorite wish, ltd co does not warrant that the functions or content contained in this site will be uninterrupted or error-free, that defects will be corrected, or that this site or the server that makes it available are free of viruses or other harmful components. Favorite wish, ltd co does not warrant or make any representation regarding use, or the result of use, of the content in terms of accuracy, reliability, or otherwise. The content may include technical inaccuracies or typographical errors, and favorite wish, ltd co may make changes or improvements at any time. You, and not favorite wish, ltd co, assume the entire cost of all necessary servicing, repair or correction in the event of any loss or damage arising from the use of this site or its content. Favorite wish, ltd co makes no warranties that your use of the content will not infringe the rights of others and assumes no liability or responsibility for errors or omissions in such content.</p>
                    <p>All of the information in this site, whether historical in nature or forward-looking, speaks only as of the date the information is posted on this site, and FAVORITE WISH, LTD CO does not undertake any obligation to update such information after it is posted or to remove such information from this site if it is not, or is no longer accurate or complete.</p>
                    <h3>10.  LIMITATION ON LIABILITY</h3>
                    <p>Favorite wish, ltd co, its subsidiaries, affiliates, licensors, service providers, content providers, employees, agents, officers, and directors will not be liable for any incidental, direct, indirect, punitive, actual, consequential, special, exemplary, or other damages, including loss of revenue or income, pain and suffering, emotional distress, or similar damages, even if favorite wish, ltd co has been advised of the possibility of such damages.</p>
                    <h3>11.  TERMINATION OR RESTRICTION OF ACCESS</h3>
                    <p>FAVORITE WISH, LTD CO reserves the right, in its sole discretion, to terminate your access to any or all of FAVORITE WISH, LTD CO's websites and the related services or any portion thereof at any time, without notice.</p>
                    <h3>12.  INDEMNITY</h3>
                    <p>You will indemnify and hold FAVORITE WISH, LTD CO, its subsidiaries, affiliates, licensors, content providers, service providers, employees, agents, officers, directors, and contractors (the “Indemnified Parties”) harmless from any breach of these Terms of Use by you, including any use of Content other than as expressly authorized in these Terms of Use. You agree that the Indemnified Parties will have no liability in connection with any such breach or unauthorized use, and you agree to indemnify any and all resulting loss, damages, judgments, awards, costs, expenses, and attorneys' fees of the Indemnified Parties in connection therewith. You will also indemnify and hold the Indemnified Parties harmless from and against any claims brought by third parties arising out of your use of the information accessed from this site.</p>
                    <h3>13.  TRADEMARKS AND COPYRIGHTS</h3>
                    <p>The trademarks, trade names, service marks, and logos (“Trademarks”) appearing on this Website, including without limitation FAVORITE WISH, LTD CO® and/or its distinctive logo.  All other content on this Website (“Copyrights”), including all page headers, custom graphics, button icons, and scripts are copyrighted works of FAVORITE WISH, LTD CO, and may not be copied, imitated or used, in whole or in part, without the prior written permission of FAVORITE WISH, LTD CO.  From time to time, the website will legally utilize intellectual property owned by third parties related to our services.  The rights in any third party trademarks or copyrighted works on this Website are retained by their respective owners.  Nothing in this Agreement shall confer any right of ownership of any of the Trademarks or Copyrights to you.  Further, nothing in this Agreement shall be construed as granting, by implication, estoppel or otherwise, any license or right to use any Trademark or Copyright without the express written permission of FAVORITE WISH, LTD CO.  The misuse of the Trademark or Copyrighted works displayed in this site, or any other content on the site, is strictly prohibited and may expose you to liability.</p>
                    <p>All contents of FAVORITE WISH, LTD CO's websites are: Copyright © FAVORITE WISH, LTD CO.  All rights reserved.</p>
                    <h3>14.  COPYRIGHT INFRINGEMENT</h3>
                    <h5>Notice and Takedown Procedure</h5>
                    <p>FAVORITE WISH, LTD CO expeditiously responds to valid notices of copyright infringement that adhere to the requirements set forth in the Digital Millennium Copyright Act (DMCA). If you believe that your work has been copied in a way that constitutes copyright infringement, you may provide FAVORITE WISH, LTD CO's Designated Agent (listed below) with a notice that contains all six points enumerated below (preferably via email).</p>
                    <p>Upon receipt of a valid notice, FAVORITE WISH, LTD CO will remove or disable access to the allegedly infringing content as well as make a good-faith attempt to contact the owner or administrator of the affected content so they may counter-notice pursuant to Sections 512(g)(2) and (3) of the DMCA.</p>
                    <ul>
                        <li>An electronic or physical signature of the person authorized to act on behalf of the owner of the copyright interest;</li>
                        <li>A description of the copyrighted work that you claim has been infringed upon;</li>
                        <li>A description of where the material that you claim is infringing is located on the site, including the URL, if applicable;</li>
                        <li>Your address, telephone number, and e-mail address;</li>
                        <li>A statement by you that you have a good-faith belief that the disputed use is not authorized by the copyright owner, its agent, or the law; and,</li>
                        <li>A statement by you, made under penalty of perjury, that the above information in your notice is accurate and that you are the copyright owner or authorized to act on the copyright owner's behalf.</li>
                    </ul>
                    <p>Be aware that a notice must contain all six points for FAVORITE WISH, LTD CO to take action. All other notices will be ignored.</p>
                    <h3>Designated Agent:</h3>
                    <p>FAVORITE WISH, LTD CO’s Designated Agent can be can be contacted at:</p>
                    <p>e-mail: tgbtg@favoritewish.com</p>
                    <h3>Counter-Notification Procedure</h3>
                    <p>The provider of the allegedly infringing content may make a counter-notification pursuant to sections 512(g)(2) and (3) of the DMCA. To file a counter-notification with FAVORITE WISH, LTD CO please provide FAVORITE WISH, LTD CO’s Designated Agent (listed above) with the following information (preferably via email):</p>
                    <ul>
                        <li>Identification of the material that has been removed or to which access has been disabled and the location at which the material appeared before it was removed or access to it was disabled;</li>
                        <li>Your name, address, and telephone number;</li>
                        <li>The following statement: “I consent to the jurisdiction of Federal District Court for the [insert the federal judicial district in which your address is located]”;</li>
                        <li>The following statement: “I will accept service of process from [insert the name of the person who submitted the infringement notification] or his/her agent”;</li>
                        <li>The following statement: “I swear, under penalty of perjury, that I have a good faith belief that the affected material was removed or disabled as a result of a mistake or misidentification of the material to be removed or disabled”; and</li>
                        <li>Your signature, in physical or electronic form.</li>
                    </ul>
                    <p>Upon receipt of a counter-notification containing all six points, FAVORITE WISH, LTD CO will promptly provide the person who provided the original takedown notification with a copy of the counter-notification, and inform that person that FAVORITE WISH, LTD CO will replace the removed material or cease disabling access to it in 10 business days.</p>
                    <p>Finally, if FAVORITE WISH, LTD CO’s Designated Agent receives notification from the person who submitted the original takedown notification within 14 days of receipt of the counter-notification that an action has been filed seeking a court order to restrain the alleged infringer from engaging in infringing activity relating to the material on its system, then FAVORITE WISH, LTD CO will once again remove the file from its system.</p>
                    <h3>Repeat Infringers</h3>
                    <p>In accordance with Section 512(i)(1)(a) of the DMCA, FAVORITE WISH, LTD CO will, in appropriate circumstances, disable and/or terminate the accounts of users who are repeat infringers.</p>
                    <h3>Accommodation of Standard Technical Measures.</h3>
                    <p>It is FAVORITE WISH, LTD CO's policy to accommodate and not interfere with standard technical measures used by copyright owners to identify or protect copyrighted works that FAVORITE WISH, LTD CO determines are reasonable under the circumstances.</p>
                    <h3>15.  SECURITY</h3>
                    <p>Any passwords used for this site are for individual use only. You will be responsible for the security of your password (if any). FAVORITE WISH, LTD CO will be entitled to monitor your password and, at its discretion, require you to change it. If you use a password that FAVORITE WISH, LTD CO considers insecure, FAVORITE WISH, LTD CO will be entitled to require the password to be changed and/or terminate your account.</p>
                    <p>You are prohibited from using any services or facilities provided in connection with this site to compromise security or tamper with system resources and/or accounts. The use or distribution of tools designed for compromising security (e.g., password guessing programs, cracking tools or network probing tools) is strictly prohibited. If you become involved in any violation of system security, FAVORITE WISH, LTD CO reserves the right to release your details to system administrators at other sites in order to assist them in resolving security incidents. FAVORITE WISH, LTD CO reserves the right to investigate suspected violations of these Terms of Use.</p>
                    <p>FAVORITE WISH, LTD CO reserves the right to fully cooperate with any law enforcement authorities or court order requesting or direction FAVORITE WISH, LTD CO to disclose the identity of anyone posting any e-mail messages, or publishing or otherwise making available any materials that are believed to violate these Terms of Use. By accepting this agreement you waive and hold harmless favorite wish, ltd co from any claims resulting from any action taken by favorite wish, ltd co during or as a result of its investigations and/or from any actions taken as a consequence of investigations by either favorite wish, ltd co or law enforcement authorities.</p>
                    <h3>16.  MISCELLANEOUS</h3>
                    <p>These Terms of Use will be governed and interpreted pursuant to the laws of South Carolina, United States of America, notwithstanding any principles of conflicts of law. You specifically consent to personal jurisdiction in South Carolina in connection with any dispute between you and FAVORITE WISH, LTD CO arising out of these Terms of Use or pertaining to the subject matter hereof. The parties to these Terms of Use each agree that the exclusive venue for any dispute between the parties arising out of these Terms of Use will be in the state and federal courts in York County , South Carolina.</p>
                    <p>If any part of these Terms of Use is unlawful, void or unenforceable, that part will be deemed severable and will not affect the validity and enforceability of any remaining provisions.</p>
                    <p>You agree that no joint venture, partnership, employment, or agency relationship exists between you and FAVORITE WISH, LTD CO as a result of this agreement or use of FAVORITE WISH, LTD CO’s websites.</p>
                    <p>These Terms of Use constitute the entire agreement among the parties relating to this subject matter and supersedes all prior or contemporaneous communications and proposals, whether electronic, oral or written between the user and FAVORITE WISH, LTD CO with respect to FAVORITE WISH, LTD CO's websites.</p>
                    <p>A printed version of this agreement and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to this agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form.</p>
                    <p>The Terms of Use may not be assigned by you without our prior written consent, however, the Terms of Use may be assigned by us in our sole discretion.</p>
                    <p>Notwithstanding the foregoing, any additional terms and conditions on this site will govern the items to which they pertain.</p>
                    <p>FAVORITE WISH, LTD CO may revise these Terms of Use at any time by updating this posting.</p>
                </div>
            </div>
        </div>
    </div>
</section>